=== 1ukash/3dCharts-web/war/coords.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="plotdata" type="PlotDataType" />

	<xs:complexType name="PlotDataType">
		<xs:sequence>
			<xs:element name="data" type="DataType" minOccurs="1"
				maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="DataType">
		<xs:sequence>
			<xs:element name="values" type="ValuesType" minOccurs="1"
				maxOccurs="3" />
		</xs:sequence>
		<xs:attribute name="id" type="xs:int" />
	</xs:complexType>

	<xs:complexType name="ValuesType">
		<xs:sequence>
			<xs:element name="value" type="xs:decimal" minOccurs="1"
				maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attributeGroup ref="ValuesAttrs" />
	</xs:complexType>

	<xs:attributeGroup name="ValuesAttrs">
		<xs:attribute name="axis" type="xs:string" />
		<xs:attribute name="name" type="xs:string" />
		<xs:attribute name="type" type="xs:string" />
	</xs:attributeGroup>

</xs:schema>

=== 1ukash/3dCharts-web/war/coords.xml
<?xml version="1.0" encoding="utf-8"?>

<plotdata xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="coords.xsd">

	<data id='1'>
		<values axis='x' name='XCOORDS' type='int'>
			<value>1</value>
			<value>4</value>
			<value>1</value>
			<value>3</value>
			<value>10</value>
			<value>5</value>
		</values>

		<values axis='y' name='YCOORDS' type='double'>
			<value>2.0</value>
			<value>1.0</value>
			<value>19.2</value>
			<value>45.1</value>
			<value>1.28</value>
			<value>5.55</value>
		</values>

		<values axis='z' name='ZCOORDS' type='double'>
			<value>5.0</value>
			<value>4.0</value>
			<value>13.2</value>
			<value>15.1</value>
			<value>1.28</value>
			<value>5.0</value>
		</values>
	</data>

	<data id='2'>
		<values axis='x' name='XCOORDS' type='int'>
			<value>18838</value>
			<value>24181</value>
		</values>

		<values axis='y' name='YCOORDS' type='double'>
			<value>2.0</value>
			<value>1.0</value>
		</values>

		<values axis='z' name='ZCOORDS' type='double'>
			<value>2.0</value>
			<value>1.0</value>
		</values>
	</data>


</plotdata>
